sudo: false
language: ruby
before_install:
- openssl aes-256-cbc -K $encrypted_6fb9a2b3fb6c_key -iv $encrypted_6fb9a2b3fb6c_iv
  -in keys.tar.enc -out keys.tar -d
- ruby ./setup.rb $@
script:
  - echo 0
